spring: 
  application:
    name: microservice-discovery-eureka-HA
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: eureka-peer1
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8080/eureka/,http://eureka-peer2:8080/eureka/
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: eureka-peer2
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8080/eureka/,http://eureka-peer2:8080/eureka/
