server:
  port: 9001
logging:
  file: common-microservice-eureka-client-9001.log
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@10.167.202.129:8761}/eureka/