server:
  port: 8080
logging:
  file: common-microservice-docker.log
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
management: 
  security: 
    enabled: false
eureka:
  client:
    serviceUrl: 
      defaultZone: http://10.167.202.129:8761/eureka/
    healthcheck:
      enabled: true