server:
  port: 9102
logging:
  file: common-microservice-logservice.log
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
management: 
  security: 
    enabled: false
eureka:
  client:
    serviceUrl: 
      defaultZone: http://apisec.fedwallet.net:8282/eureka/
    healthcheck:
      enabled: true