spring:
  application:
    name: springboot-ui
  boot: 
    admin: 
      routes: 
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine: 
        clusters: default
        location: turbine
management: 
  security: 
    enabled: false
logging:
  file: common-microservice-springboot-ui.log
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
server:
  port: 8000
eureka:  
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://poc-4.novalocal:8761}/eureka/
